[package]
name = "replay-traffic-from-logs"
version = "0.1.0"
authors = ["davidpdrsn"]

[dependencies]
instant-replay = { git = "https://github.com/tonsser/instant-replay.git" }
postgres = { version = "0.15", features = ["with-openssl"] }
dotenv = "0.10.1"
openssl = "0.9.19"
