#!/usr/bin/env ruby

thread_count = 1
minutes = 1.0
duration = (minutes * 60).round

puts "Running benchmark with config:"
puts "thread_count = #{thread_count}"
puts "duration = #{duration}"

system "heroku run --size performance-l ./target/release/replay-traffic-from-logs --thread-count #{thread_count} --duration #{duration}"

puts "thread_count = #{thread_count}"
puts "duration = #{duration}"
